In [ ]:
import tensorflow as tf

print("TensorFlow version: ", tf.__version__)
print("Keras version: ", tf.keras.__version__)

In [ ]:
import tensorflow as tf
import tensorflow.keras as keras

print("TensorFlow version: ", tf.__version__)
print("Keras version: ", keras.__version__)

In [1]:
import tensorflow as tf

if tf.test.is_gpu_available():
    print('Running on GPU')
else:
    print('Running on CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
Running on CPU


In [ ]:
import tensorflow as tf
import numpy as np

# create a ndarray
an_array = np.array([1,3,5,7,11])
print(type(an_array), an_array)

a_tensor = tf.convert_to_tensor(an_array)
print(a_tensor)

In [ ]:
# convert from tensor to ndarray
array_2 = a_tensor.numpy()
print(type(array_2), array_2)

In [ ]:
import tensorflow as tf
import numpy as np

# create a 2x3 aray
an_array = np.array([[1,2],
                     [3,4],
                     [5,6]])

# convert to tensor
a_tensor = tf.convert_to_tensor(an_array)

# no. of elements on each axis
print(a_tensor.shape)
# data type
print(a_tensor.dtype)

# no. of axises
print(a_tensor.ndim)

In [ ]:
# input from list
import tensorflow as tf
import numpy as np

# create a ndarray
an_array = [1, 2, 3, 4, 5]
print(type(an_array), an_array)

# convert from ndarray to tensor
a_tensor = tf.convert_to_tensor(an_array)
print(a_tensor)

# convert from tensor to ndarray
array_2 = a_tensor.numpy()
print(type(array_2), array_2)

In [ ]:
import tensorflow as tf
import numpy as np

# create two tensors
tensor_1 = tf.convert_to_tensor([[1,2],
                                 [3,4]])
tensor_2 = tf.convert_to_tensor([1])

# add two tensors
tensor_3 = tensor_1 + tensor_2

print('tensor_1: \n', tensor_1)
print('tensor_2: \n', tensor_2)
print('tensor_3: \n', tensor_3)

In [ ]:
import tensorflow as tf
import numpy as np

# create 2x2 tensor
tensor_1 = tf.convert_to_tensor([[1,2],
                                 [3,4]])

# add a number to a tensor 
tensor_2 = tensor_1 + 2

print('tensor_1: \n', tensor_1)
print('tensor_2: \n', tensor_2)

In [ ]:
import tensorflow as tf
import numpy as np

# create 4x3 tensor
np_data = np.array(range(1, 13)).reshape(4, 3)
tensor_1 = tf.convert_to_tensor(np_data)

# create the second tensor
tensor_2 = tf.convert_to_tensor([1, 0, 1])

# add a number to a tensor 
tensor_3 = tensor_1 + tensor_2

print('tensor_1: \n', tensor_1)
print('tensor_2: \n', tensor_2)
print('tensor_3: \n', tensor_3)

In [6]:
import tensorflow as tf
import numpy as np

matrix = tf.convert_to_tensor([[1, 2], [3, 4]])
vector = tf.convert_to_tensor([1, 2])

print('matrix 1 shape \n', matrix.shape)

vector = tf.reshape(vector, (2, 1))
print('matrix 2 reshape \n', vector.shape)

result1 = tf.matmul(matrix, vector)
print(result1)

result2 = tf.matmul(tf.transpose(vector), matrix)
print(result2)

matrix 1 shape 
 (2, 2)
matrix 2 reshape 
 (2, 1)
tf.Tensor(
[[ 5]
 [11]], shape=(2, 1), dtype=int32)
tf.Tensor([[ 7 10]], shape=(1, 2), dtype=int32)


In [ ]:
import tensorflow as tf
import numpy as np

matrix1 = tf.convert_to_tensor([[1, 2], [3, 4]])
matrix2 = tf.convert_to_tensor([[2, 3], [2, 1]])

print('matrix1 shape \n', matrix1.shape)
print('matrix2 shape \n', matrix2.shape)

result1 = tf.matmul(matrix1, matrix2)
print(result1)

result2 = tf.matmul(matrix2, matrix1)
print(result2)

In [ ]:
import tensorflow as tf
import numpy as np

matrix1 = tf.convert_to_tensor([[1, 2], [3, 4]])
matrix2 = tf.convert_to_tensor([[2, 3], [2, 1]])

print('matrix1 shape \n', matrix1.shape)
print('matrix2 shape \n', matrix2.shape)

result1 = matrix1@matrix2
print(result1)

result2 = matrix2@matrix1
print(result2)

In [8]:
var = tf.Variable([1.0, 2.0])
var = var + 1
print(var)

tf.Tensor([2. 3.], shape=(2,), dtype=float32)


In [ ]:
# variable

var = tf.Variable([1.0, 2.0])
print(var.numpy())

var.assign([7, 9])
print(var.numpy())

In [ ]:
# variables

var = tf.Variable([1.0, 2.0])

var.assign_add([5, 3])
print(var.numpy())

var.assign_sub([2, 3])
print(var.numpy())

In [ ]:
import tensorflow as tf
import numpy as np

# create an ndarray
x = np.array([1,2, 3, 4])
y = 5

# compute squared difference
sd = tf.math.squared_difference(x,y)
print(sd)

In [9]:
import tensorflow as tf

rand = tf.random.normal(shape=(4,2), mean=0, stddev=0.1)
print(rand)

tf.Tensor(
[[-0.0944895  -0.05738968]
 [-0.06031917 -0.03671269]
 [-0.03285211 -0.05531168]
 [-0.06464849  0.04467383]], shape=(4, 2), dtype=float32)


In [ ]:
import tensorflow as tf

rand = tf.random.uniform(shape=(9,9), minval=0, 
                         maxval=9, dtype=tf.int32)
print(rand)

In [ ]:
import tensorflow as tf

tensor_1 = tf.random.normal(shape=(2,2), mean=0, stddev=1)
tensor_2 = tf.random.normal(shape=(2,2), mean=0, stddev=1)

# concat two tensors along axis_0
tensor_3 = tf.concat([tensor_1, tensor_1], axis=0)

# concat two tensors along axis_1
tensor_4 = tf.concat([tensor_1, tensor_1], axis=1)

print(tensor_1.shape)
print(tensor_2.shape)
print(tensor_3.shape)
print(tensor_4.shape)

In [ ]:
import tensorflow as tf

# create a tensor
a_tensor = tf.constant([6, 2, 8, 5, 4, 7, 1])

# find the index of the max value
max_position = tf.argmax(a_tensor)

# find the index of the min value
min_position = tf.argmin(a_tensor)

print(a_tensor)
print('max_position: ', max_position)
print('min_position: ', min_position)

In [ ]:
import tensorflow as tf

# create a tensor
tensor = tf.random.uniform(shape=(3,6), minval=0, 
                         maxval=20, dtype=tf.int32)

# find the index of the max value
max_position_1 = tf.argmax(tensor, axis=0)
max_position_2 = tf.argmax(tensor, axis=1)

print(tensor)
print('max_position_1: ', max_position_1)
print('max_position_2: ', max_position_2)

In [ ]:
import tensorflow as tf

# create a tensor
tensor = tf.random.uniform(shape=(3,6), minval=0, 
                         maxval=20, dtype=tf.int32)

# find the index of the min value
min_position_1 = tf.argmin(tensor, axis=0)
min_position_2 = tf.argmin(tensor, axis=1)

print(tensor)
print('min_position_1: ', min_position_1)
print('min_position_2: ', min_position_2)

In [ ]:
import tensorflow as tf

x = [1, 2, 3, 4]
sum_value = tf.reduce_sum(x)
print(sum_value)

In [ ]:
import tensorflow as tf

y_true = [[0, 1, 0], [0, 0, 1]]
y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
y_pred = tf.convert_to_tensor(y_pred)

# CategoricalCrossentropy
ce_function = tf.keras.losses.CategoricalCrossentropy()
loss = ce_function(y_true, y_pred)

print(loss.numpy())

In [ ]:
import tensorflow as tf

y_true = [1, 2]
y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
y_pred = tf.convert_to_tensor(y_pred)

# SparseCategoricalCrossentropy
sce_function = tf.keras.losses.SparseCategoricalCrossentropy()
loss = sce_function(y_true, y_pred)
print(loss.numpy())

In [1]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(3,)))
model.add(keras.layers.Dense(1))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [2]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(4,)))
model.add(keras.layers.Dense(3))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [3]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(4,)))
model.add(keras.layers.Dense(3))
model.add(keras.layers.Activation(keras.activations.softmax))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 3)                 15        
                                                                 
 activation (Activation)     (None, 3)                 0         
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [4]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(1,)))
model.add(keras.layers.Dense(1))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [5]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(3,)))
model.add(keras.layers.Dense(1))

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 1)                 4         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [6]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(13,)))
model.add(keras.layers.Dense(1))

model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 1)                 14        
                                                                 
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [7]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(1,)))
model.add(keras.layers.Dense(2))
model.add(keras.layers.Activation(keras.activations.softmax))

model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 2)                 4         
                                                                 
 activation_1 (Activation)   (None, 2)                 0         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [8]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(1,)))
model.add(keras.layers.Dense(2, activation='softmax'))

model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 2)                 4         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [9]:
import tensorflow as tf
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(1,)))
model.add(keras.layers.Dense(3, activation='softmax'))

model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 3)                 6         
                                                                 
Total params: 6
Trainable params: 6
Non-trainable params: 0
_________________________________________________________________


In [10]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(4,)))
model.add(keras.layers.Dense(3, activation='softmax'))

model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [11]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [12]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(2,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_11 (Dense)            (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [13]:
import tensorflow.keras as keras

# create model
model = keras.Sequential()
model.add(keras.Input(shape=(4,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 1)                 5         
                                                                 
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________
