In [1]:
# Tải file data
!gdown --id 1O8q12g0VnWlu3ZZJvJdL1siWJqgpmzsI

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1O8q12g0VnWlu3ZZJvJdL1siWJqgpmzsI
To: /content/data.csv
100% 31.0/31.0 [00:00<00:00, 50.3kB/s]


In [2]:
import numpy as np
import torch
import torch.nn as nn

# Data Preparation
data = np.genfromtxt('data.csv', delimiter=',')
X = torch.from_numpy(data[:,0:1])
y = torch.from_numpy(data[:,1:])

print(X)
print(y)

tensor([[6.7000],
        [4.6000],
        [3.5000],
        [5.5000]], dtype=torch.float64)
tensor([[9.1000],
        [5.9000],
        [4.6000],
        [6.7000]], dtype=torch.float64)


In [ ]:
#Create model liner regression
linear_model = nn.Linear(1, 1)

In [ ]:
print(linear_model)
list(linear_model.parameters())

Linear(in_features=1, out_features=1, bias=True)


[Parameter containing:
 tensor([[-0.1769]], requires_grad=True), Parameter containing:
 tensor([0.7114], requires_grad=True)]

In [ ]:
loss_fn = nn.MSELoss()

In [ ]:
optimizer = torch.optim.SGD(linear_model.parameters(), lr=0.00004)

In [ ]:
from torch.autograd import Variable
data = np.genfromtxt('data.csv', delimiter=',')
X = Variable(torch.tensor(data[:,0:1])).float()
y = Variable(torch.tensor(data[:,1:])).float()

print(X)
print(y)

tensor([[6.7000],
        [4.6000],
        [3.5000],
        [5.5000]])
tensor([[9.1000],
        [5.9000],
        [4.6000],
        [6.7000]])


In [ ]:
import torch
from torch.autograd import Variable

class LinearRegressionModel(torch.nn.Module):

	def __init__(self):
		super(LinearRegressionModel, self).__init__()
		self.linear = torch.nn.Linear(1, 1) # One in and one out

	def forward(self, x):
		y_pred = self.linear(x)
		return y_pred

# our model
our_model = LinearRegressionModel()

criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(our_model.parameters(), lr = 0.001)

for epoch in range(100):

	# Forward pass: Compute predicted y by passing
	# x to the model
	pred_y = our_model(X)

	# Compute and print loss
	loss = criterion(pred_y, y)

	# Zero gradients, perform a backward pass,
	# and update the weights.
	optimizer.zero_grad()
	loss.backward()
	optimizer.step()
	print('epoch {}, loss {}'.format(epoch, loss.item()))


epoch 0, loss 27.351436614990234
epoch 1, loss 24.38535499572754
epoch 2, loss 21.743154525756836
epoch 3, loss 19.389476776123047
epoch 4, loss 17.29281234741211
epoch 5, loss 15.425092697143555
epoch 6, loss 13.761323928833008
epoch 7, loss 12.279230117797852
epoch 8, loss 10.958975791931152
epoch 9, loss 9.782886505126953
epoch 10, loss 8.735220909118652
epoch 11, loss 7.8019561767578125
epoch 12, loss 6.970600128173828
epoch 13, loss 6.23002290725708
epoch 14, loss 5.570311546325684
epoch 15, loss 4.98263692855835
epoch 16, loss 4.459133625030518
epoch 17, loss 3.992793083190918
epoch 18, loss 3.5773727893829346
epoch 19, loss 3.2073140144348145
epoch 20, loss 2.8776614665985107
epoch 21, loss 2.5840044021606445
epoch 22, loss 2.322410821914673
epoch 23, loss 2.089381217956543
epoch 24, loss 1.8817944526672363
epoch 25, loss 1.6968746185302734
epoch 26, loss 1.5321450233459473
epoch 27, loss 1.3854005336761475
epoch 28, loss 1.254678726196289
epoch 29, loss 1.1382288932800293
epoch

In [ ]:
new_var = Variable(torch.Tensor([[4.0]]))
pred_y = our_model(new_var)
print("predict (after training)", 4, our_model(new_var).item())

predict (after training) 4 5.444839000701904


In [ ]:
our_model.state_dict()

OrderedDict([('linear.weight', tensor([[1.1021]])),
             ('linear.bias', tensor([1.0365]))])

In [ ]:
for param_tensor in our_model.state_dict():
    print(param_tensor, "\t", our_model.state_dict()[param_tensor].size())

linear.weight 	 torch.Size([1, 1])
linear.bias 	 torch.Size([1])


In [ ]:
torch.save(our_model.state_dict(), "ln.pt")

In [ ]:
model = LinearRegressionModel()

In [ ]:
model.load_state_dict(torch.load("/content/ln.pt"))

<All keys matched successfully>

In [ ]:
model.eval()

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [ ]:
new_var = Variable(torch.Tensor([[4.0]]))
pred_y = model(new_var)
print("predict (after training)", 4, model(new_var).item())

predict (after training) 4 5.444839000701904


In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [16]:
# Data Preparation
data = np.genfromtxt('data.csv', delimiter=',')
X = torch.tensor(data[:,0:1], dtype = torch.float)
y = torch.tensor(data[:,1:], dtype = torch.float)

print(X)
print(y)

tensor([[6.7000],
        [4.6000],
        [3.5000],
        [5.5000]])
tensor([[9.1000],
        [5.9000],
        [4.6000],
        [6.7000]])


In [17]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [18]:
# Define dataset
train_ds = TensorDataset(X, y)
train_ds[0:3]

(tensor([[6.7000],
         [4.6000],
         [3.5000]]), tensor([[9.1000],
         [5.9000],
         [4.6000]]))

In [19]:
batch_size = 2
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

[tensor([[5.5000],
         [3.5000]]), tensor([[6.7000],
         [4.6000]])]

In [20]:
class my_network(nn.Module):
  def __init__(self):
    super().__init__()
    self.liner1 = nn.Linear(1,1)
  def forward(self, x):
    x = self.liner1(x)
    return x  

In [21]:
model = my_network()

In [25]:
opt = torch.optim.SGD(model.parameters(), 0.01)

In [26]:
loss_fn = F.mse_loss

In [27]:
# Define a utility function to train the model
def fit(datatrain, num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(X), y))


In [28]:
fit(train_dl, 100, model, loss_fn, opt)

Training loss:  tensor(0.0878, grad_fn=<MseLossBackward0>)
