# **PYTORCH BASIC**

## INTRODUCT TO PYTORCH

In [ ]:
import torch
import numpy as np

In [ ]:
#create  a numpy array
arr_np = np.arange(10)
print(arr_np)
print(arr_np.shape)

#convert a numpy array to tensor
tensor_arr = torch.from_numpy(arr_np)
print(tensor_arr)

#convert tensor to numpy
arr_np_back = tensor_arr.numpy()
print(arr_np_back)
print(arr_np_back.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
[0 1 2 3 4 5 6 7 8 9]
(10,)


### Create a tensor


In [ ]:
#from list
list_1 = [[1, 2, 3],
          [4, 5, 6]]
torch_from_list = torch.tensor(list_1)
print(torch_from_list)
print(torch_from_list[0])
print(torch_from_list[1])
print(torch_from_list[0,1])

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3])
tensor([4, 5, 6])
tensor(2)


### Attributes of a tensor 

In [ ]:
tensor = torch.tensor([[1, 2, 3, 4], [4, 3, 2, 1]])
print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])
Shape of tensor: torch.Size([2, 4])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


### Common Atributes

In [ ]:
# Tao torch tu 1 so, duoc goi la scalar
import torch
data = torch.tensor(3)
print(data)
print(data.shape)

tensor(3)
torch.Size([])


In [ ]:
#Tao tensor tu 1 list
import torch

#Tao list
list_1D = [1, 2, 3, 4]
#Tao tensor
data = torch.tensor(list_1D)

print(data)
print(data.shape)


tensor([1, 2, 3, 4])
torch.Size([4])


In [ ]:
import torch

#Tao list
list_2D = [[1, 2], [3, 4], [5, 6]]
#Tao tensor
data = torch.tensor(list_2D)

print(data)
print(data.shape)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [ ]:
import torch

#Tao list
list_3D = [[[1, 2], [3, 4]],
           [[5, 6], [7, 8]],
           [[9,10], [11, 12]]]
#Tao tensor
data = torch.tensor(list_3D)

print(data)
print(data.shape)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
torch.Size([3, 2, 2])


In [ ]:
#dtype example
data1 = torch.tensor([1, 2, 3])
print(data1)
print(data1.dtype)

data2 = torch.tensor([3.14, 2.14, 2.16])
print(data2.dtype)
print(data2)

data3 = torch.tensor([1, 2, 3], dtype=float)
print(data3.dtype)
print(data3)

tensor([1, 2, 3])
torch.int64
torch.float32
tensor([3.1400, 2.1400, 2.1600])
torch.float64
tensor([1., 2., 3.], dtype=torch.float64)


### Update an element

In [ ]:
#Thay doi gia tri phan tu trong tensor
import torch

#Khoi tao list
l = list(range(1,4))

#Tao torch
data = torch.tensor(l)
print(data)

#Thay doi gia tri cua phan tu thu nhat trong tensor
data[0] = 100
print(data)

tensor([1, 2, 3])
tensor([100,   2,   3])


### Create tensor

In [ ]:
#Tao 1 tensor toan so 0
import torch
tensor0 = torch.zeros((3, 4))
print(tensor0)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
#Tao 1 tensor toan so 1
import torch
tensor1 = torch.ones((3, 4))
print(tensor1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
#Tao 1 tensor voi tat ca phan tu la hang so
import torch
tensor_instance_value = torch.full((3, 4), 33)
print(tensor_instance_value)

tensor([[33, 33, 33, 33],
        [33, 33, 33, 33],
        [33, 33, 33, 33]])


In [ ]:
#arrange function
import torch

torch_arange = torch.arange(5)
print(torch_arange)

torch_arrange_2 = torch.arange(-10, 10, 3)
print(torch_arrange_2)

torch_arrange_2 = torch.arange(-10, 10, 3)
print(torch_arrange_2)

tensor([0, 1, 2, 3, 4])
tensor([-10,  -7,  -4,  -1,   2,   5,   8])


In [ ]:
#Tao 1 tensor voi duong cheo chinh la so 1, cac phan tu con lai =0
import torch

torch_eye = torch.eye(3,3)
torch_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
#Tao 1 tensor voi cac gia tri ngau nhien
import torch

torch_random = torch.rand((2, 3))
print(torch_random)


tensor([[0.7824, 0.8800, 0.8176],
        [0.8380, 0.3435, 0.5907]])


### Some important functions

#### Clip

In [ ]:
#clip
import torch

torch_random = torch.randint(-100,100,(3,3))
print(torch_random)

torch_clip = torch.clip(torch_random, min=1, max=4)
print(torch_clip)

tensor([[-59,  94,  41],
        [-93,  58, -99],
        [ 31, -37,  30]])
tensor([[1, 4, 4],
        [1, 4, 1],
        [4, 1, 4]])


In [ ]:
import torch
data = torch.tensor([1, 2, 3, 4, 5])
min_list = [1, 4, 9, -19, 3]
max_list = [9, 10, 11, -2, 4]
#clip value
results = np.clip(data, a_min = min_list, a_max= max_list)
print(results)

tensor([ 1,  4,  9, -2,  4])


#### hstask

In [ ]:
#hstack(horizontal stack)  Ket hop tensor theo chieu ngang
torch1 = torch.tensor([1, 2, 3])
torch2 = torch.tensor([4, 5, 6])

result = torch.hstack((torch1, torch2))
print("torch1:", torch1)
print("torch2:", torch2)
print("results", results)


torch1: tensor([1, 2, 3])
torch2: tensor([4, 5, 6])
results tensor([ 1,  4,  9, -2,  4])


In [ ]:
#hstack 
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.hstack((a,b))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

#### vstack

In [ ]:
#vstack(vertical stack) ket hop tensor theo chieu doc
torch1 = torch.tensor([1, 2, 3])
torch2 = torch.tensor([4, 5, 6])

results = torch.vstack((torch1, torch2))
print("torch1:", torch1)
print("torch2:", torch2)
print("results", results)

torch1: tensor([1, 2, 3])
torch2: tensor([4, 5, 6])
results tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
#vstack 
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.vstack((a,b))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

#### concatenate


In [ ]:
#concatenate Noi hai tensor theo chieu ngang hoac chieu doc
tensor1 = torch.ones((3,4))
print("tensor 1:", tensor1)

tensor2 = torch.zeros((3,4))
print("tensor 2:", tensor2)

#Noi theo chieu doc
concanate_tensor = torch.concat((tensor1, tensor2), 0)
print("concanate_tensor:",concanate_tensor)

#Noi theo chieu ngang
concanate_tensor = torch.concat((tensor1, tensor2), 1)
print("concanate_tensor:",concanate_tensor)

tensor 1: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor 2: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
concanate_tensor: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
concanate_tensor: tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])


In [ ]:
tensor1 = torch.ones((3,))
print("tensor 1:", tensor1)

tensor2 = torch.zeros((3,))
print("tensor 2:", tensor2)

#Noi theo chieu doc
concanate_tensor = torch.concat((tensor1, tensor2), 0)
print("concanate_tensor:",concanate_tensor)

#Noi theo chieu ngang
concanate_tensor = torch.concat((tensor1, tensor2), 1)
print("concanate_tensor:",concanate_tensor)

tensor 1: tensor([1., 1., 1.])
tensor 2: tensor([0., 0., 0.])
concanate_tensor: tensor([1., 1., 1., 0., 0., 0.])


IndexError: ignored

5. Add more dimensions

In [ ]:
t1 = torch.rand((3,))
print(t1, t1.shape)

#Cach 1: Su dung None de lap chi muc

# 1D--->2D
t1 = t1[None,:]
print(t1.shape)

tensor([0.9804, 0.7677, 0.8093]) torch.Size([3])
torch.Size([1, 3])


In [ ]:
# 1D--->3D
t1 = torch.rand((3,))
print(t1, t1.shape)
t1 = t1[None,None]
print(t1.shape)

tensor([0.8026, 0.6325, 0.8382]) torch.Size([3])
torch.Size([1, 1, 3])


In [ ]:
#1D--->3D
t1 = torch.rand((3,))
print(t1, t1.shape)

t1 = t1[:, None,None]
print(t1.shape)

tensor([0.3964, 0.1056, 0.3091]) torch.Size([3])
torch.Size([3, 1, 1])


In [ ]:
# 1D--->2D
print("1D------->2D")
t1 = torch.rand((3,))
print(t1, t1.shape)
t1 = t1[None,:]
print(t1.shape)

print("2D------->3D")
t1 = t1[None,:]
print(t1.shape)

print("3D------->5D")
t1 = t1[None,None,:]
print(t1.shape)

1D------->2D
tensor([0.7706, 0.9095, 0.2699]) torch.Size([3])
torch.Size([1, 3])
2D------->3D
torch.Size([1, 1, 3])
3D------->5D
torch.Size([1, 1, 1, 1, 3])


In [ ]:
#Cach 2: su dung PyTorch Unsqueeze
# 1D--->2D
x = torch.randn(16)
print(x.shape)
x = torch.unsqueeze(x, dim=0)
print(x.shape)

# 2D--->3D
x = torch.unsqueeze(x, dim=(2))
print(x.shape)

torch.Size([16])
torch.Size([1, 16])
torch.Size([1, 16, 1])


In [ ]:
# Them 1 chieu vao cuoi
x = torch.randn(16)
print(x.shape)
x = torch.unsqueeze(x, dim=-1)
print(x.shape)

torch.Size([16])
torch.Size([16, 1])


6. Apply along axis function
Note: Ham nay khong co san

In [ ]:
t1 = torch.rand((3,3))

In [ ]:
print(t1)

tensor([[0.0890, 0.5005, 0.3961],
        [0.6825, 0.1086, 0.6724],
        [0.0888, 0.0994, 0.2383]])


In [ ]:
t2 = t1.numpy()
print(t2)
t3 = np.apply_along_axis(np.diag, -1, t2)
print(t3)

[[0.9680993  0.01273572 0.21204251]
 [0.12959105 0.19527131 0.65940005]
 [0.11239374 0.72365487 0.1455617 ]]
[[[0.9680993  0.         0.        ]
  [0.         0.01273572 0.        ]
  [0.         0.         0.21204251]]

 [[0.12959105 0.         0.        ]
  [0.         0.19527131 0.        ]
  [0.         0.         0.65940005]]

 [[0.11239374 0.         0.        ]
  [0.         0.72365487 0.        ]
  [0.         0.         0.1455617 ]]]


In [ ]:
t1 = torch.from_numpy(t3)
print(t1)

tensor([[[0.9681, 0.0000, 0.0000],
         [0.0000, 0.0127, 0.0000],
         [0.0000, 0.0000, 0.2120]],

        [[0.1296, 0.0000, 0.0000],
         [0.0000, 0.1953, 0.0000],
         [0.0000, 0.0000, 0.6594]],

        [[0.1124, 0.0000, 0.0000],
         [0.0000, 0.7237, 0.0000],
         [0.0000, 0.0000, 0.1456]]])


7 Compare

In [ ]:
import torch

t1 = torch.randint(-10, 10, (20,))
print(t1)
t2 = torch.randint(-10, 10, (20,))
print(t2)

tensor([-5,  9,  7, -9,  9, -6, -2,  4,  0, -1, -6, -4,  8, -4, -1,  0,  5, -9,
        -5,  6])
tensor([ -9, -10,   5,   4,   0,  -4,   9,  -7,   9,   8,   2,   7,  -3,   9,
         -2,  -1,  -7,   3,   5,  -8])


In [ ]:
def compare(a, b):
  if a>=b:
    return 0
  else:
    return 1

In [ ]:
compare(1, 2)

1

In [ ]:
compare(t1, t2)

RuntimeError: ignored

In [ ]:
compare_vec = np.vectorize(compare)

t1_to_np = t1.numpy()
t2_to_np = t2.numpy()

results = compare_vec(t1_to_np, t2_to_np)
print(results)

[0 0 0 1 0 1 1 0 1 1 1 1 0 1 0 0 0 1 1 0]


In [ ]:
results_tensor = torch.from_numpy(results)

In [ ]:
results_tensor

tensor([0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0])

#### Where, flatten, reshape

In [ ]:
import torch

#Tao 1 tensor
t = torch.tensor([[1, 2, 3, 4],
                  [5, 1, 10, -9],
                  [1, 3, 24, -6]])
#condition
condition = t<5
print(condition)

#where
out = torch.where(condition, 0, t*2)
print(out)

tensor([[ True,  True,  True,  True],
        [False,  True, False,  True],
        [ True,  True, False,  True]])
tensor([[ 0,  0,  0,  0],
        [10,  0, 20,  0],
        [ 0,  0, 48,  0]])


In [ ]:
#flatten
t = torch.tensor([[1, 2, 3, 4],
                  [5, 1, 10, -9],
                  [1, 3, 24, -6]])
out = torch.flatten(t)
print(t)
print(out)

tensor([[ 1,  2,  3,  4],
        [ 5,  1, 10, -9],
        [ 1,  3, 24, -6]])
tensor([ 1,  2,  3,  4,  5,  1, 10, -9,  1,  3, 24, -6])


In [ ]:
#reshape
t = torch.ones_like(t)
print(t)
print(t.shape)


tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
torch.Size([3, 4])


In [ ]:
torch.reshape(t, (4,3))

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.reshape(t, (2,6))

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])

In [ ]:
torch.reshape(t, (2, 2 ,3))

tensor([[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]])

# TENSOR INDEXING

## Slicing

In [ ]:
#slicing

t1 = torch.randint(-100, 100, (3,3))
print(t1)
print(t1[0,1])
print(t1[:, 1])
print(t1[0:1, 0])
print(t1[:,:])

tensor([[-48,  63,  86],
        [ 99,  23,  61],
        [ 61, -24, -50]])
tensor(63)
tensor([ 63,  23, -24])
tensor([-48])
tensor([[-48,  63,  86],
        [ 99,  23,  61],
        [ 61, -24, -50]])


In [ ]:
#slicing
import torch

#Khoi tao 1 tensor
t1 = torch.tensor([[1, 2, 3],
                  [5, 6, 7]])
#Su dung slicing de tao tensor t2 bang cach lay tat ca dong va cot
t2 = t1[:, 1:3]

print(t1)
print(t2)

tensor([[1, 2, 3],
        [5, 6, 7]])
tensor([[2, 3],
        [6, 7]])


In [ ]:
#Mutable
import torch

#Khoi tao 1 tensor
t1 = torch.tensor([[1, 2, 3],
                  [5, 6, 7]])
#Su dung slicing de tao tensor t2 bang cach lay tat ca dong va cot
t2 = t1[:, 1:3]

print(t1)
print(t2)

t2[0,0] = 99

print(t2)
print(t1)


tensor([[1, 2, 3],
        [5, 6, 7]])
tensor([[2, 3],
        [6, 7]])
tensor([[99,  3],
        [ 6,  7]])
tensor([[ 1, 99,  3],
        [ 5,  6,  7]])


## Get a row

In [ ]:
#Get a row
#Tao 1 tensor co kic co 3x3 
t1 = torch.randint(1, 10, (3, 3))
print(t1, t1.shape)

tensor([[3, 4, 5],
        [7, 7, 6],
        [6, 3, 3]]) torch.Size([3, 3])


In [ ]:
#cach 1: So chiu giam  
t2 = t1[1, :]
#cach 2: so chieu giu nguyen
t3 = t1[1:2, :]

print(t2, t2.shape)
print(t3, t3.shape)

tensor([6, 5, 4]) torch.Size([3])
tensor([[6, 5, 4]]) torch.Size([1, 3])


##Get a column

In [ ]:
#Get a column

#Tao 1 tensor co kic co 3x3 
t1 = torch.randint(1, 10, (3, 3))
print(t1, t1.shape)

#cach 1: So chiu giam  
t2 = t1[:, 1]
#cach 2: so chieu giu nguyen
t3 = t1[:, 1:2]

print(t2, t2.shape)
print(t3, t3.shape)

tensor([[2, 6, 9],
        [1, 1, 1],
        [4, 6, 5]]) torch.Size([3, 3])
tensor([6, 1, 6]) torch.Size([3])
tensor([[6],
        [1],
        [6]]) torch.Size([3, 1])


##Using lists as indices

In [ ]:
#Using lists as indices

t1 = torch.randint(1, 10, (3, 3))
print(t1, t1.shape)

#Lay gia tri tai vi tri (0,0), (1, 1), (2, 0)
out1 = t1[[0, 1, 2], [0, 1, 0]]
print(out1)

#Có thể truy xuất 1 phần tử nhiều lần cùng lúc
out2 = t1[[0, 0, 0], [1, 1, 1]]
print(out2)



tensor([[4, 9, 7],
        [2, 5, 5],
        [2, 6, 2]]) torch.Size([3, 3])
tensor([4, 5, 2])
tensor([9, 9, 9])


##Boolean indices

In [ ]:
#Boolean indices
t1 = torch.randint(1, 10, (3, 3))
print(t1, t1.shape)

#Tim cac phan tu lon hon 2
bool_idx = t1>2
print(bool_idx)

tensor([[1, 8, 8],
        [2, 5, 8],
        [8, 5, 3]]) torch.Size([3, 3])
tensor([[False,  True,  True],
        [False,  True,  True],
        [ True,  True,  True]])


In [ ]:
t1 = torch.randint(1, 10, (3, 3))
print(t1, t1.shape)

#Tim cac phan tu lon hon 2
bool_idx = t1>2
print(bool_idx)
#get satisfying  elements
result = t1[bool_idx]
print(results)

tensor([[7, 4, 5],
        [2, 7, 2],
        [9, 6, 6]]) torch.Size([3, 3])
tensor([[ True,  True,  True],
        [False,  True, False],
        [ True,  True,  True]])
[0 0 0 1 0 1 1 0 1 1 1 1 0 1 0 0 0 1 1 0]


##Addition

In [ ]:
#Addition
import torch

t1 = torch.randint(1, 10, (10,))
t2 = torch.randint(1, 10, (10,))

print("t1:",t1)
print("t2:",t2)

#tong hai tensor 
print("method 1\n", t1+t2)
print("method 2\n", torch.add(t1, t2))

t1: tensor([7, 1, 6, 4, 7, 5, 8, 4, 4, 3])
t2: tensor([9, 7, 4, 1, 8, 6, 2, 8, 5, 1])
method 1
 tensor([16,  8, 10,  5, 15, 11, 10, 12,  9,  4])
method 2
 tensor([16,  8, 10,  5, 15, 11, 10, 12,  9,  4])


##Subtraction

In [ ]:
#Subtraction 
import torch

t1 = torch.randint(1, 10, (10,))
t2 = torch.randint(1, 10, (10,))

print("t1:",t1)
print("t2:",t2)

#hieu hai tensor 
print("method 1\n", t1-t2)
print("method 2\n", torch.sub(t1, t2))

t1: tensor([3, 6, 7, 7, 7, 7, 4, 5, 5, 7])
t2: tensor([3, 5, 6, 7, 7, 8, 5, 7, 8, 9])
method 1
 tensor([ 0,  1,  1,  0,  0, -1, -1, -2, -3, -2])
method 2
 tensor([ 0,  1,  1,  0,  0, -1, -1, -2, -3, -2])


##Multiplication

In [ ]:
#Multiplication 
import torch

t1 = torch.randint(1, 10, (10,))
t2 = torch.randint(1, 10, (10,))

print("t1:",t1)
print("t2:",t2)

#tich hai tensor
print("method 1\n", t1*t2)
print("method 2\n", torch.mul(t1, t2))

t1: tensor([6, 3, 8, 3, 4, 7, 2, 4, 8, 1])
t2: tensor([9, 4, 3, 4, 1, 1, 4, 3, 7, 4])
method 1
 tensor([54, 12, 24, 12,  4,  7,  8, 12, 56,  4])
method 2
 tensor([54, 12, 24, 12,  4,  7,  8, 12, 56,  4])


##Division 

In [ ]:
#Division 
import torch

t1 = torch.randint(1, 10, (10,))
t2 = torch.randint(1, 10, (10,))

print("t1:",t1)
print("t2:",t2)

#tich hai tensor
print("method 1\n", t1/t2)
print("method 2\n", torch.div(t1, t2))

t1: tensor([3, 7, 7, 2, 3, 1, 7, 9, 4, 7])
t2: tensor([7, 9, 3, 4, 7, 5, 3, 9, 9, 6])
method 1
 tensor([0.4286, 0.7778, 2.3333, 0.5000, 0.4286, 0.2000, 2.3333, 1.0000, 0.4444,
        1.1667])
method 2
 tensor([0.4286, 0.7778, 2.3333, 0.5000, 0.4286, 0.2000, 2.3333, 1.0000, 0.4444,
        1.1667])


##Square root

In [ ]:
#Square root
import torch

t1 = torch.randint(1, 10, (10,))
print("t1\n", t1)

#Can bac hai cua tung phan tu trong tensor
print("sqrt t1:\n", torch.sqrt(data))


t1
 tensor([3, 8, 1, 4, 4, 1, 4, 8, 4, 6])
sqrt t1:
 tensor([1.0000, 1.4142, 1.7321, 2.0000, 2.2361])


##Inner product

In [ ]:
#Inner product
import torch

t1 = torch.randint(1, 10, (10,))
t2 = torch.randint(1, 10, (10,))

print("t1:",t1)
print("t2:",t2)

#Tinh inner product giữa t1 và t2

print("method 1 \n", torch.dot(t1, t2))
print("method 2 \n", t1.dot(t2))
print("method 3 \n", t1@t2)

t1: tensor([2, 6, 2, 6, 5, 4, 7, 3, 9, 8])
t2: tensor([7, 4, 8, 4, 4, 6, 3, 7, 2, 6])
method 1 
 tensor(230)
method 2 
 tensor(230)
method 3 
 tensor(230)


##Vector-matrix multiplication

In [ ]:
#Vector-matrix multiplication
t1 = torch.randint(1, 10, (2,))
t2 = torch.randint(1, 10, (2,2))

print(t1,"\n", t2)
#Phap nhan giua ma tran va vecto
print("t1xt2:", t1.matmul(t2))

tensor([3, 9]) 
 tensor([[1, 4],
        [5, 9]])
t1xt2: tensor([48, 93])


In [ ]:
print("t2xt1:", torch.dot(t2,t1))

RuntimeError: ignored

In [ ]:
print("t2xt1:", torch.matmul(t2,t1))

t2xt1: tensor([93, 42])


##Matrix-matrix multiplication

In [ ]:
#Matrix-matrix multiplication
t1 = torch.randint(1, 10, (2,2))
t2 = torch.randint(1, 10, (2,2))

print(t1,"\n", t2)
#Phap nhan giua ma tran va ma tran
print("t1xt2:", t1.matmul(t2))

tensor([[8, 7],
        [1, 1]]) 
 tensor([[3, 7],
        [7, 6]])
t1xt2: tensor([[73, 98],
        [10, 13]])


##Transpose

In [ ]:
#Transpose
t1 = torch.randint(1, 10, (3,5))
print(t1, t1.shape)
print(t1.T, t1.T.shape)

tensor([[2, 4, 6, 4, 6],
        [4, 5, 5, 4, 7],
        [2, 6, 6, 8, 8]]) torch.Size([3, 5])
tensor([[2, 4, 2],
        [4, 5, 6],
        [6, 5, 6],
        [4, 4, 8],
        [6, 7, 8]]) torch.Size([5, 3])


##Sumation

In [ ]:
#Sumation
t1 = torch.randint(1, 10, (3,5))
print(t1, t1.shape)

#Tong cac phan tu cua tensor
print(torch.sum(t1))
#Tinh tong theo tung cot
print(torch.sum(t1, axis=0))
#Tinh tong theo tung hang
print(torch.sum(t1, axis=1))

tensor([[6, 1, 2, 9, 7],
        [9, 1, 9, 9, 5],
        [9, 1, 1, 1, 2]]) torch.Size([3, 5])
tensor(72)
tensor([24,  3, 12, 19, 14])
tensor([25, 33, 14])


##Max and min

In [ ]:
#Max and min
t1 = torch.randint(1, 10, (3,5))
print(t1, t1.shape)

print(t1.min())
print(t1.max())

tensor([[4, 2, 6, 1, 9],
        [6, 6, 3, 9, 8],
        [3, 7, 3, 3, 1]]) torch.Size([3, 5])
tensor(1)
tensor(9)


In [ ]:
print(t1.min(axis = 0))
print(t1.max(axis = 1))

torch.return_types.min(
values=tensor([3, 2, 3, 1, 1]),
indices=tensor([2, 0, 1, 0, 2]))
torch.return_types.max(
values=tensor([9, 9, 7]),
indices=tensor([4, 3, 1]))


# Broadcasting


In [ ]:
#vector and a scalar
t1 = torch.randint(1, 10, (3,5))
print(t1, t1.shape)

t2 = 2

#broadcasting
result_multiplication = t1*t2
result_minus = t1 - t2

print(result_multiplication)
print(result_minus)

tensor([[6, 9, 2, 5, 2],
        [1, 7, 1, 4, 3],
        [3, 5, 7, 1, 9]]) torch.Size([3, 5])
tensor([[12, 18,  4, 10,  4],
        [ 2, 14,  2,  8,  6],
        [ 6, 10, 14,  2, 18]])
tensor([[ 4,  7,  0,  3,  0],
        [-1,  5, -1,  2,  1],
        [ 1,  3,  5, -1,  7]])


In [ ]:
#mtrix and vector
import torch

t1 = torch.randint(1, 10, (10,10))
t2 = torch.randint(1, 10, (10,))

print("t1:",t1)
print("t2:",t2)

t3 = t1 +t2
print("t3:",t3)

t1: tensor([[2, 1, 9, 4, 5, 9, 2, 7, 5, 3],
        [4, 7, 2, 1, 1, 1, 5, 8, 3, 7],
        [7, 1, 6, 8, 7, 9, 5, 1, 2, 5],
        [2, 8, 1, 5, 3, 6, 9, 9, 3, 1],
        [6, 4, 3, 2, 5, 6, 2, 5, 8, 6],
        [2, 7, 5, 4, 8, 4, 8, 9, 9, 2],
        [8, 5, 4, 8, 1, 6, 3, 4, 8, 8],
        [1, 4, 2, 4, 4, 7, 9, 6, 9, 8],
        [8, 9, 5, 6, 5, 8, 7, 7, 4, 8],
        [1, 5, 6, 2, 3, 9, 9, 3, 1, 7]])
t2: tensor([6, 8, 3, 5, 5, 3, 2, 4, 5, 6])
t3: tensor([[ 8,  9, 12,  9, 10, 12,  4, 11, 10,  9],
        [10, 15,  5,  6,  6,  4,  7, 12,  8, 13],
        [13,  9,  9, 13, 12, 12,  7,  5,  7, 11],
        [ 8, 16,  4, 10,  8,  9, 11, 13,  8,  7],
        [12, 12,  6,  7, 10,  9,  4,  9, 13, 12],
        [ 8, 15,  8,  9, 13,  7, 10, 13, 14,  8],
        [14, 13,  7, 13,  6,  9,  5,  8, 13, 14],
        [ 7, 12,  5,  9,  9, 10, 11, 10, 14, 14],
        [14, 17,  8, 11, 10, 11,  9, 11,  9, 14],
        [ 7, 13,  9,  7,  8, 12, 11,  7,  6, 13]])
