In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# Create some basic tensor

#create  a numpy array
arr_np = np.arange(10)
print(arr_np)
print(arr_np.shape)

#create a tensor 
tensor_arr = tf.constant(arr_np)
print(tensor_arr)

#convert tensor to numpy
arr_np_back = tensor_arr.numpy()
print(arr_np_back)
print(arr_np_back.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int64)
[0 1 2 3 4 5 6 7 8 9]
(10,)


In [4]:
#create  a numpy array
arr_np = np.arange(10)
print(arr_np)
print(arr_np.shape)

#convert a numpy array to tensor
tensor_arr = tf.convert_to_tensor(arr_np)
print(tensor_arr)

#convert tensor to numpy
arr_np_back = tensor_arr.numpy()
print(arr_np_back)
print(arr_np_back.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int64)
[0 1 2 3 4 5 6 7 8 9]
(10,)


In [5]:
arr_np = np.arange(10)
print(arr_np)
print(arr_np.shape)

#convert a numpy array to tensor
tensor_arr = tf.convert_to_tensor(arr_np)
print(tensor_arr)
tensor_arr[2]

[0 1 2 3 4 5 6 7 8 9]
(10,)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int64)


<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [6]:
tensor_arr[1]

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [7]:
from tensorflow.python.framework.ops import convert_to_tensor
#from list
list_1 = [[1, 2, 3],
          [4, 5, 6]]
tensor_from_list = convert_to_tensor(list_1)
print(tensor_from_list)
print(tensor_from_list[0])
print(tensor_from_list[1])
print(tensor_from_list[0,1])

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


### Attributes of a tensor 

In [8]:
tensor = tf.convert_to_tensor([[1, 2, 3, 4], [4, 3, 2, 1]])
print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tf.Tensor(
[[1 2 3 4]
 [4 3 2 1]], shape=(2, 4), dtype=int32)
Shape of tensor: (2, 4)
Datatype of tensor: <dtype: 'int32'>
Device tensor is stored on: /job:localhost/replica:0/task:0/device:CPU:0


### Common Atributes

In [9]:
# Tao tensor tu 1 so, duoc goi la scalar
import tensorflow as tf
data = tf.convert_to_tensor(3)
print(data)
print(data.shape)

tf.Tensor(3, shape=(), dtype=int32)
()


In [10]:
#Tao tensor tu 1 list
import tensorflow as tf

#Tao list
list_1D = [1, 2, 3, 4]
#Tao tensor
data = tf.convert_to_tensor(list_1D)

print(data)
print(data.shape)


tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
(4,)


In [11]:
import tensorflow as tf

#Tao list
list_2D = [[1, 2], [3, 4], [5, 6]]
#Tao tensor
data = tf.convert_to_tensor(list_2D)

print(data)
print(data.shape)


tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
(3, 2)


In [12]:
import tensorflow as tf

#Tao list
list_3D = [[[1, 2], [3, 4]],
           [[5, 6], [7, 8]],
           [[9,10], [11, 12]]]
#Tao tensor
data = tf.convert_to_tensor(list_3D)

print(data)
print(data.shape)

tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int32)
(3, 2, 2)


In [13]:
#dtype example
data1 = tf.convert_to_tensor([1, 2, 3])
print(data1)
print(data1.dtype)

data2 = tf.convert_to_tensor([3.14, 2.14, 2.16])
print(data2.dtype)
print(data2)

data3 = tf.convert_to_tensor([1, 2, 3], dtype=float)
print(data3.dtype)
print(data3)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<dtype: 'int32'>
<dtype: 'float32'>
tf.Tensor([3.14 2.14 2.16], shape=(3,), dtype=float32)
<dtype: 'float32'>
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


### Update an element


In [14]:
#Variance ex1
#Khoi tao 1 variable
var = tf.Variable([1.0, 2.0])
print(var.numpy())
#Thay doi gia tri cua variable voi asign
var.assign([7, 9])
print(var.numpy())

[1. 2.]
[7. 9.]


In [ ]:
#Thay doi gia tri phan tu trong variable 
import tensorflow as tf

#Khoi tao list
l = list(range(1,4))

#Tao variance
data = tf.Variable(l)
print(data)

#Thay doi gia tri cua phan tu thu nhat trong tensor
print(data[0])
data[0] = 100
print(data[0])

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
tf.Tensor(1, shape=(), dtype=int32)


TypeError: ignored

In [101]:
tf.random.set_seed(111)

tensor = tf.random.uniform((2, 4), minval=0, maxval=5, dtype=tf.int32)
tf.print(tensor, '\n')

index1 = [0, 3]
index2 = [1, 1]
indices = [index1, index2]
updates = [50, 60]

tf.print(tf.tensor_scatter_nd_update(tensor, indices, updates))

[[0 4 1 4]
 [2 1 2 3]] 

[[0 4 1 50]
 [2 60 2 3]]


In [21]:
#Tao 1 tensor toan so 0
import tensorflow as tf
tensor0 = tf.zeros((3, 4))
print(tensor0)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [22]:
#Tao 1 tensor toan so 1
import tensorflow as tf
tensor1 = tf.ones((3, 4))
print(tensor1)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [24]:
#Tao 1 tensor voi tat ca phan tu la hang so
import tensorflow as tf
tensor_instance_value = tf.fill((3, 4), 33)
print(tensor_instance_value)

tf.Tensor(
[[33 33 33 33]
 [33 33 33 33]
 [33 33 33 33]], shape=(3, 4), dtype=int32)


In [28]:
#range function
import tensorflow as tf

tensor_range = tf.range(5)
print(tensor_range)

tensor_range_2 = tf.range(-10, 10, 2)
print(tensor_range_2)

tensor_range_3 = tf.range(-10, 10, 3)
print(tensor_range_3)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([-10  -8  -6  -4  -2   0   2   4   6   8], shape=(10,), dtype=int32)
tf.Tensor([-10  -7  -4  -1   2   5   8], shape=(7,), dtype=int32)


In [29]:
#Tao 1 tensor voi duong cheo chinh la so 1, cac phan tu con lai =0
import tensorflow as tf

tensor_eye = tf.eye(3,3)
tensor_eye

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [32]:
#Tao 1 tensor voi cac gia tri ngau nhien
import tensorflow as tf

tensor_random = tf.random.uniform((2, 3))
print(tensor_random)


tf.Tensor(
[[0.86369586 0.60063684 0.95674896]
 [0.7128948  0.50341344 0.9982449 ]], shape=(2, 3), dtype=float32)


### Some important functions

#### Clip

In [38]:
#clip
import tensorflow as tf

tensor_random = tf.random.uniform((3,3),  minval=-100, maxval=100)
print(tensor_random)

tensor_clip = tf.clip_by_value(tensor_random, clip_value_min=1, clip_value_max=4)
print(tensor_clip)

tf.Tensor(
[[-32.095    -34.87558  -68.99309 ]
 [-50.02916   53.719376 -86.17308 ]
 [-83.3075   -92.4345    27.717354]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]], shape=(3, 3), dtype=float32)


In [40]:
import tensorflow as tf

data = tf.constant([1, 2, 3, 4, 5])
min_list = [1, 4, 9, -19, 3]
max_list = [9, 10, 11, -2, 4]
#clip value
results = tf.clip_by_value(data, clip_value_min=min_list, clip_value_max=max_list)
print(results)

tf.Tensor([ 1  4  9 -2  4], shape=(5,), dtype=int32)


#### hstask

In [45]:
#hstack(horizontal stack)  Ket hop tensor theo chieu ngang
tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([4, 5, 6])

result = tf.stack((tensor1, tensor2), axis = 1)
print("tensor1:", tensor1)
print("tensor2:", tensor2)
print("results", results)


tensor1: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tensor2: tf.Tensor([4 5 6], shape=(3,), dtype=int32)
results tf.Tensor([ 1  4  9 -2  4], shape=(5,), dtype=int32)


In [46]:
#hstack 
a = tf.constant([[1],[2],[3]])
b = tf.constant([[4],[5],[6]])
tf.stack((a,b), axis = 1)

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [4]],

       [[2],
        [5]],

       [[3],
        [6]]], dtype=int32)>

#### vstack

In [48]:
#vstack(vertical stack) ket hop tensor theo chieu doc
tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([4, 5, 6])

results = torch.stack((tensor1, tensor2), axis = 0)
print("tensor1:", tensor1)
print("tensor2:", tensor2)
print("results", results)

NameError: ignored

In [50]:
#vstack 
a = tf.constant([[1],[2],[3]])
b = tf.constant([[4],[5],[6]])
tf.stack((a,b), axis = 0)

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

#### concatenate


In [51]:
#concatenate Noi hai tensor theo chieu ngang hoac chieu doc
tensor1 = tf.ones((3,4))
print("tensor 1:", tensor1)

tensor2 = tf.zeros((3,4))
print("tensor 2:", tensor2)

#Noi theo chieu doc
concanate_tensor = tf.concat((tensor1, tensor2), 0)
print("concanate_tensor:",concanate_tensor)

#Noi theo chieu ngang
concanate_tensor = tf.concat((tensor1, tensor2), 1)
print("concanate_tensor:",concanate_tensor)

tensor 1: tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
tensor 2: tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)
concanate_tensor: tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(6, 4), dtype=float32)
concanate_tensor: tf.Tensor(
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]], shape=(3, 8), dtype=float32)


In [52]:
tensor1 = tf.ones((3,))
print("tensor 1:", tensor1)

tensor2 = tf.zeros((3,))
print("tensor 2:", tensor2)

#Noi theo chieu doc
concanate_tensor = tf.concat((tensor1, tensor2), 0)
print("concanate_tensor:",concanate_tensor)

#Noi theo chieu ngang, khoong noi duoc vi day la tonsor 1 chieu nen chieu 1 khong ton tai
concanate_tensor = tf.concat((tensor1, tensor2), 1)
print("concanate_tensor:",concanate_tensor)

tensor 1: tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tensor 2: tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
concanate_tensor: tf.Tensor([1. 1. 1. 0. 0. 0.], shape=(6,), dtype=float32)


InvalidArgumentError: ignored

####Add more dimensions

In [53]:
t1 = tf.random.uniform((3,))
print(t1, t1.shape)

#Cach 1: Su dung None de lap chi muc

# 1D--->2D
t1 = t1[None,:]
print(t1.shape)

tf.Tensor([0.21828926 0.83551097 0.74849343], shape=(3,), dtype=float32) (3,)
(1, 3)


In [54]:
# 1D--->3D
t1 = tf.random.uniform((3,))
print(t1, t1.shape)
t1 = t1[None,None]
print(t1.shape)

tf.Tensor([0.11755705 0.12099016 0.8643302 ], shape=(3,), dtype=float32) (3,)
(1, 1, 3)


In [55]:
#1D--->3D
t1 = tf.random.uniform((3,))
print(t1, t1.shape)

t1 = t1[:, None,None]
print(t1.shape)

tf.Tensor([0.3464328  0.5132257  0.34922528], shape=(3,), dtype=float32) (3,)
(3, 1, 1)


In [56]:
# 1D--->2D
print("1D------->2D")
t1 = tf.random.uniform((3,))
print(t1, t1.shape)
t1 = t1[None,:]
print(t1.shape)

print("2D------->3D")
t1 = t1[None,:]
print(t1.shape)

print("3D------->5D")
t1 = t1[None,None,:]
print(t1.shape)

1D------->2D
tf.Tensor([0.32593167 0.8267096  0.18861532], shape=(3,), dtype=float32) (3,)
(1, 3)
2D------->3D
(1, 1, 3)
3D------->5D
(1, 1, 1, 1, 3)


In [61]:
#Cach 2: su dung expand_dims
# 1D--->2D
x = tf.random.uniform((16,))
print(x.shape)
x = tf.expand_dims(x, axis=0)
print(x.shape)

# 2D--->3D
x = tf.expand_dims(x, axis=(2))
print(x.shape)

(16,)
(1, 16)
(1, 16, 1)


In [63]:
# Them 1 chieu vao cuoi
x = tf.random.uniform((16,))
print(x.shape)
x = tf.expand_dims(x, axis=(-1))
print(x.shape)

(16,)
(16, 1)


6. Apply along axis function <=> tf.map_fn

In [64]:
# Example: RaggedTensor input
rt = tf.ragged.constant([[1, 2, 3], [], [4, 5], [6]])
tf.map_fn(tf.reduce_sum, rt, fn_output_signature=tf.int32)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([6, 0, 9, 6], dtype=int32)>

7 Compare

In [65]:
#So sanh lon hon
x = tf.constant([5, 4, 6])
y = tf.constant([5, 2, 5])
print(tf.math.greater(x, y) )

x = tf.constant([5, 4, 6])
y = tf.constant([5])
print(tf.math.greater(x, y))

tf.Tensor([False  True  True], shape=(3,), dtype=bool)
tf.Tensor([False False  True], shape=(3,), dtype=bool)


In [66]:
#So sanh bang
x = tf.constant([5, 4, 6, 7])
y = tf.constant([5, 2, 5, 10])
print(tf.math.greater_equal(x, y) )

x = tf.constant([5, 4, 6, 7])
y = tf.constant([5])
print(tf.math.greater_equal(x, y) )

tf.Tensor([ True  True  True False], shape=(4,), dtype=bool)
tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


#### Where, flatten, reshape

In [67]:
import tensorflow as tf


#Tao 1 tensor
t = tf.constant([[1, 2, 3, 4],
                  [5, 1, 10, -9],
                  [1, 3, 24, -6]])
#condition
condition = t<5
print(condition)

#where
out = tf.where(condition, 0, t*2)
print(out)

tf.Tensor(
[[ True  True  True  True]
 [False  True False  True]
 [ True  True False  True]], shape=(3, 4), dtype=bool)
tf.Tensor(
[[ 0  0  0  0]
 [10  0 20  0]
 [ 0  0 48  0]], shape=(3, 4), dtype=int32)


In [76]:
#Vi flatten khong co san(chi co trong keras) nen chung ta co the dung reshape 
t = tf.constant([[1, 2, 3, 4],
                  [5, 1, 10, -9],
                  [1, 3, 24, -6]])
t = tf.reshape(t, [-1])
out = t.get_shape()
print(t)
print(out)

tf.Tensor([ 1  2  3  4  5  1 10 -9  1  3 24 -6], shape=(12,), dtype=int32)
(12,)


In [78]:
#reshape
t = tf.constant([[1, 2, 3, 4],
                  [5, 1, 10, -9],
                  [1, 3, 24, -6]])
print(t)
print(t.shape)


tf.Tensor(
[[ 1  2  3  4]
 [ 5  1 10 -9]
 [ 1  3 24 -6]], shape=(3, 4), dtype=int32)
(3, 4)


In [79]:
tf.reshape(t, (4,3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  1],
       [10, -9,  1],
       [ 3, 24, -6]], dtype=int32)>

In [80]:
tf.reshape(t, (2,6))

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  1],
       [10, -9,  1,  3, 24, -6]], dtype=int32)>

In [81]:
tf.reshape(t, (2, 2 ,3))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  1]],

       [[10, -9,  1],
        [ 3, 24, -6]]], dtype=int32)>

# TENSOR INDEXING

## Slicing

In [82]:
#slicing

t1 = tf.random.uniform((3,3), minval = -100, maxval =100)
print(t1)
print(t1[0,1])
print(t1[:, 1])
print(t1[0:1, 0])
print(t1[:,:])

tf.Tensor(
[[ 76.516266 -18.289139  49.314194]
 [-62.28869  -64.78989   51.13542 ]
 [ 62.239258 -75.24874   28.698318]], shape=(3, 3), dtype=float32)
tf.Tensor(-18.289139, shape=(), dtype=float32)
tf.Tensor([-18.289139 -64.78989  -75.24874 ], shape=(3,), dtype=float32)
tf.Tensor([76.516266], shape=(1,), dtype=float32)
tf.Tensor(
[[ 76.516266 -18.289139  49.314194]
 [-62.28869  -64.78989   51.13542 ]
 [ 62.239258 -75.24874   28.698318]], shape=(3, 3), dtype=float32)


In [84]:
#slicing
import tensorflow as tf

#Khoi tao 1 tensor
t1 = tf.constant([[1, 2, 3],
                  [5, 6, 7]])
#Su dung slicing de tao tensor t2 bang cach lay tat ca dong va cot
t2 = t1[:, 1:3]

print(t1)
print(t2)

tf.Tensor(
[[1 2 3]
 [5 6 7]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [85]:
#Mutable
import tensorflow as tf

#Khoi tao 1 tensor
t1 = tf.constant([[1, 2, 3],
                  [5, 6, 7]])
#Su dung slicing de tao tensor t2 bang cach lay tat ca dong va cot
t2 = t1[:, 1:3]

print(t1)
print(t2)

#Khong gong numpy hoac pytorch, chung ta khong the thay doi gia tri trong 1 tensor
t2[0,0] = 99

print(t2)
print(t1)


tf.Tensor(
[[1 2 3]
 [5 6 7]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


TypeError: ignored

In [92]:
t1[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [107]:
#Tuy nhien, van co the thay doi bang cach su dung ham sau tf.tensor_scatter_nd_update
indices=[[0,0]]
updates=[2]
tf.print(tf.tensor_scatter_nd_update(t1, indices, updates))


[[2 2 3]
 [5 6 7]]


## Get a row

In [108]:
#Get a row
#Tao 1 tensor co kic co 3x3 
t1 = tf.random.uniform((3, 3), maxval= 10, minval= 1)
print(t1, t1.shape)

tf.Tensor(
[[8.773263  6.4057317 9.610741 ]
 [7.4160533 5.5307207 9.984204 ]
 [6.050125  4.392494  8.476948 ]], shape=(3, 3), dtype=float32) (3, 3)


In [109]:
#cach 1: So chiu giam  
t2 = t1[1, :]
#cach 2: so chieu giu nguyen
t3 = t1[1:2, :]

print(t2, t2.shape)
print(t3, t3.shape)

tf.Tensor([7.4160533 5.5307207 9.984204 ], shape=(3,), dtype=float32) (3,)
tf.Tensor([[7.4160533 5.5307207 9.984204 ]], shape=(1, 3), dtype=float32) (1, 3)


##Get a column

In [110]:
#Get a column

#Tao 1 tensor co kic co 3x3 
t1 = tf.random.uniform((3, 3), maxval= 10, minval= 1)
print(t1, t1.shape)

#cach 1: So chiu giam  
t2 = t1[:, 1]
#cach 2: so chieu giu nguyen
t3 = t1[:, 1:2]

print(t2, t2.shape)
print(t3, t3.shape)

tf.Tensor(
[[7.1335006 9.432911  3.477138 ]
 [9.992009  5.544812  3.0378232]
 [3.9934053 1.2377596 6.331797 ]], shape=(3, 3), dtype=float32) (3, 3)
tf.Tensor([9.432911  5.544812  1.2377596], shape=(3,), dtype=float32) (3,)
tf.Tensor(
[[9.432911 ]
 [5.544812 ]
 [1.2377596]], shape=(3, 1), dtype=float32) (3, 1)


##Using lists as indices

In [116]:
#Using lists as indices - khong ho tro

t1 = tf.random.uniform((5, 5), maxval= 10, minval= 1)
print(t1, t1.shape)

#Lay gia tri tai vi tri (0,0), (1, 1), (2, 0)
out1 = t1[[0, 1 , 2]: [0, 1, 0]]
print(out1)

#Có thể truy xuất 1 phần tử nhiều lần cùng lúc
out2 = t1[[0, 0, 0], [1, 1, 1]]
print(out2)



tf.Tensor(
[[2.0580134 2.0889115 8.778972  1.4986323 9.313283 ]
 [1.9026492 5.2134476 1.0610803 2.4738717 5.007744 ]
 [8.876146  8.086346  6.8475847 1.000368  3.548121 ]
 [6.0482864 7.0511107 2.7591248 4.7179174 3.9542975]
 [6.7710667 5.4424987 9.248647  9.696607  5.623284 ]], shape=(5, 5), dtype=float32) (5, 5)


TypeError: ignored

##Boolean indices

In [117]:
#Boolean indices
t1 = tf.random.uniform((5, 5), maxval= 10, minval= 1)
print(t1, t1.shape)

#Tim cac phan tu lon hon 2
bool_idx = t1>2
print(bool_idx)

tf.Tensor(
[[4.117895  5.619031  4.1430273 8.77248   3.304423 ]
 [1.1272665 4.082544  2.5191045 6.739849  2.3706422]
 [3.5587983 5.8844132 3.2367811 7.2279243 6.680771 ]
 [4.80103   3.721528  7.482543  9.847506  2.2476177]
 [5.4167347 2.1295352 7.0062923 5.9722285 5.483868 ]], shape=(5, 5), dtype=float32) (5, 5)
tf.Tensor(
[[ True  True  True  True  True]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]], shape=(5, 5), dtype=bool)


In [119]:
t1 = tf.random.uniform((5, 5), maxval= 10, minval= -10)
print(t1, t1.shape)

#Tim cac phan tu lon hon 2
bool_idx = t1>2
print(bool_idx)
#get satisfying  elements
result = t1[bool_idx]
print(results)

tf.Tensor(
[[ 8.4560890e+00 -2.0712066e+00 -7.4573445e+00  9.5659924e+00
  -5.1289368e-01]
 [ 2.2858095e+00 -1.3282490e+00 -9.7193861e+00 -9.1842728e+00
  -4.1151786e+00]
 [-4.3569112e+00  1.2932062e+00 -5.3783655e+00  9.8270073e+00
   7.5603466e+00]
 [ 7.6691551e+00 -7.3957443e-03 -5.8940673e+00  8.1145763e-01
   6.3597374e+00]
 [-7.9740024e+00 -1.1429482e+00  6.7499619e+00  3.5310841e+00
  -7.8965330e+00]], shape=(5, 5), dtype=float32) (5, 5)
tf.Tensor(
[[ True False False  True False]
 [ True False False False False]
 [False False False  True  True]
 [ True False False False  True]
 [False False  True  True False]], shape=(5, 5), dtype=bool)
tf.Tensor([ 1  4  9 -2  4], shape=(5,), dtype=int32)


##Addition

In [121]:
#Addition
import tensorflow as tf

t1 = tf.random.uniform((5, ), maxval= 10, minval= 1)
t2 = tf.random.uniform((5, ), maxval= 10, minval= 1)

print("t1:",t1)
print("t2:",t2)

#tong hai tensor 
print("method 1\n", t1+t2)
print("method 2\n", tf.add(t1, t2))

t1: tf.Tensor([7.453327  2.9003181 3.1782434 2.742953  8.48974  ], shape=(5,), dtype=float32)
t2: tf.Tensor([2.2364683 2.8146462 7.6805964 4.603493  2.0599756], shape=(5,), dtype=float32)
method 1
 tf.Tensor([ 9.6897955  5.7149644 10.85884    7.346446  10.549716 ], shape=(5,), dtype=float32)
method 2
 tf.Tensor([ 9.6897955  5.7149644 10.85884    7.346446  10.549716 ], shape=(5,), dtype=float32)


##Subtraction

In [125]:
#Subtraction 
import tensorflow as tf

t1 = tf.random.uniform((5, 5), maxval= 10, minval= 1)
t2 = tf.random.uniform((5, 5), maxval= 10, minval= 1)

print("t1:",t1)
print("t2:",t2)

#hieu hai tensor 
print("method 1\n", t1-t2)
print("method 2\n", tf.subtract(t1, t2))

t1: tf.Tensor(
[[8.943232  4.6769886 7.7191386 2.697009  2.584455 ]
 [7.801094  8.300767  2.1138067 6.7914248 8.109707 ]
 [9.736906  6.455923  2.621404  5.0043545 4.8781557]
 [6.2218995 4.931111  2.4228368 7.803674  8.208448 ]
 [6.605422  3.6491234 4.8587375 7.90611   5.853292 ]], shape=(5, 5), dtype=float32)
t2: tf.Tensor(
[[5.1762133 6.9619894 2.4617834 9.346664  6.8802958]
 [6.644796  6.9484873 8.029017  3.9434443 2.4674838]
 [9.000761  2.7612147 6.409231  7.45008   1.4664619]
 [9.302944  6.389431  9.706345  6.402676  2.4230685]
 [4.4749517 8.598404  9.810972  4.7604065 3.5564048]], shape=(5, 5), dtype=float32)
method 1
 tf.Tensor(
[[ 3.7670183 -2.2850008  5.257355  -6.6496553 -4.2958407]
 [ 1.1562982  1.3522797 -5.9152107  2.8479805  5.6422234]
 [ 0.736145   3.6947083 -3.7878273 -2.4457254  3.4116938]
 [-3.0810447 -1.4583201 -7.283508   1.4009981  5.78538  ]
 [ 2.1304703 -4.9492807 -4.9522347  3.1457033  2.2968872]], shape=(5, 5), dtype=float32)
method 2
 tf.Tensor(
[[ 3.7670183 -2

##Multiplication

In [127]:
#Multiplication 
import tensorflow as tf

t1 = tf.random.uniform((5, 5), maxval= 10, minval= 1)
t2 = tf.random.uniform((5, 5), maxval= 10, minval= 1)

print("t1:",t1)
print("t2:",t2)

#tich hai tensor
print("method 1\n", t1*t2)
print("method 2\n", tf.multiply(t1, t2))

t1: tf.Tensor(
[[2.9065862 4.638047  4.575333  2.2209878 9.792661 ]
 [4.4133987 8.044921  5.9004097 8.355827  6.29289  ]
 [4.968189  4.5469394 6.1338983 7.649147  8.017141 ]
 [3.6802812 1.4324772 9.605053  5.5139837 2.0885477]
 [9.043547  8.861879  3.1521873 8.301735  6.4556913]], shape=(5, 5), dtype=float32)
t2: tf.Tensor(
[[9.943355  2.5805583 8.778184  2.177007  8.842386 ]
 [6.0999575 3.9090059 9.798698  9.615843  6.676241 ]
 [3.199462  1.751291  7.519742  6.596663  2.913313 ]
 [7.242399  2.621597  7.899661  2.0687413 1.8834478]
 [3.3894212 5.0810485 2.9510925 3.336646  4.0218306]], shape=(5, 5), dtype=float32)
method 1
 tf.Tensor(
[[28.901217  11.968751  40.163116   4.835106  86.590485 ]
 [26.921545  31.447643  57.816334  80.34832   42.01285  ]
 [15.895531   7.963014  46.12533   50.458847  23.356441 ]
 [26.654066   3.755378  75.87666   11.407006   3.9336705]
 [30.65239   45.027637   9.302397  27.699951  25.963697 ]], shape=(5, 5), dtype=float32)
method 2
 tf.Tensor(
[[28.901217  11

##Division 

In [129]:
#Division 
t1 = tf.random.uniform((5, 5), maxval= 10, minval= 1)
t2 = tf.random.uniform((5, 5), maxval= 10, minval= 1)

print("t1:",t1)
print("t2:",t2)

#tich hai tensor
print("method 1\n", t1/t2)
print("method 2\n", tf.divide(t1, t2))

t1: tf.Tensor(
[[5.0091696 6.4676776 9.178151  2.5222168 5.9705014]
 [2.202267  8.35145   2.052661  5.184408  8.144934 ]
 [8.257047  7.5152273 3.3986716 1.4802377 9.43908  ]
 [6.9205117 4.565671  9.029722  5.3658743 6.279423 ]
 [1.8385272 4.8198166 4.2389994 1.1102806 5.9493256]], shape=(5, 5), dtype=float32)
t2: tf.Tensor(
[[8.684799  7.5346303 2.515623  9.258809  6.186098 ]
 [3.0110464 5.038392  6.893676  8.902705  8.0998955]
 [2.9605682 3.342298  1.0003959 8.791434  3.6337233]
 [9.03515   6.2098327 4.3562202 5.4326925 9.013696 ]
 [7.313775  5.3445606 7.7559276 6.690796  3.6259995]], shape=(5, 5), dtype=float32)
method 1
 tf.Tensor(
[[0.57677436 0.8583935  3.6484604  0.27241266 0.9651482 ]
 [0.7313959  1.6575625  0.29776    0.5823408  1.0055604 ]
 [2.7890074  2.248521   3.3973267  0.16837272 2.5976331 ]
 [0.7659543  0.73523253 2.0728343  0.9877007  0.69665354]
 [0.2513787  0.9018172  0.5465496  0.16594149 1.6407409 ]], shape=(5, 5), dtype=float32)
method 2
 tf.Tensor(
[[0.57677436 0.

##Square root

In [133]:
#Square root
t1 = tf.random.uniform((5, 5), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)
print("t1\n", t1)

#Can bac hai cua tung phan tu trong tensor
print("sqrt t1:\n", tf.square(data))


t1
 tf.Tensor(
[[8 2 7 3 4]
 [1 1 4 6 5]
 [2 2 7 6 4]
 [5 7 6 2 1]
 [6 2 4 3 4]], shape=(5, 5), dtype=int32)
sqrt t1:
 tf.Tensor([ 1  4  9 16 25], shape=(5,), dtype=int32)


##Inner product

In [150]:
#Inner product
t1 = tf.random.uniform((5, ), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)

t2 = tf.random.uniform((5, ), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)

print("t1:",t1)
print("t2:",t2)

#Tinh inner product giữa t1 và t2

print("method 1 \n", tf.tensordot(t1, t2, axes =1))


t1: tf.Tensor([4 3 1 9 7], shape=(5,), dtype=int32)
t2: tf.Tensor([9 5 8 9 7], shape=(5,), dtype=int32)
method 1 
 tf.Tensor(189, shape=(), dtype=int32)


##Vector-matrix multiplication

In [162]:
#Vector-matrix multiplication
t1 = tf.random.uniform((5, ), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)
t2 = tf.random.uniform((5,5 ), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)

print(t1,"\n", t2)
#Phap nhan giua ma tran va vecto
print("t1xt2:", tf.tensordot(t1,t2, axes =1))

tf.Tensor([6 8 2 7 7], shape=(5,), dtype=int32) 
 tf.Tensor(
[[2 5 7 5 1]
 [3 1 3 6 6]
 [7 2 4 1 1]
 [3 6 9 7 6]
 [5 2 7 6 6]], shape=(5, 5), dtype=int32)
t1xt2: tf.Tensor([106  98 186 171 140], shape=(5,), dtype=int32)


In [163]:
print("t2xt1:", tf.tensordot(t2,t1, axes =1))

t2xt1: tf.Tensor([108 116  80 175 144], shape=(5,), dtype=int32)


##Matrix-matrix multiplication

In [168]:
#Matrix-matrix multiplication
t1 = tf.random.uniform((5, 5), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)
t2 = tf.random.uniform((5, 5), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)

print(t1,"\n", t2)
#Phap nhan giua ma tran va ma tran
print("t1xt2:", tf.matmul(t1,t2))

tf.Tensor(
[[5 8 8 6 2]
 [5 5 5 6 5]
 [8 6 3 9 1]
 [5 3 4 2 8]
 [2 9 4 2 1]], shape=(5, 5), dtype=int32) 
 tf.Tensor(
[[4 6 9 8 5]
 [5 2 8 5 2]
 [7 3 2 4 5]
 [7 4 9 9 8]
 [6 4 1 3 5]], shape=(5, 5), dtype=int32)
t1xt2: tf.Tensor(
[[170 102 181 172 139]
 [152  99 154 154 133]
 [152 109 208 190 144]
 [125  88 103 113 107]
 [101  54 117  98  69]], shape=(5, 5), dtype=int32)


##Transpose

In [175]:
#Transpose
t1 = tf.random.uniform((5, 3), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)
print(t1, t1.shape)
print(tf.transpose(t1), tf.transpose(t1).shape )

tf.Tensor(
[[2 3 2]
 [6 9 8]
 [9 5 9]
 [4 9 7]
 [4 7 8]], shape=(5, 3), dtype=int32) (5, 3)
tf.Tensor(
[[2 6 9 4 4]
 [3 9 5 9 7]
 [2 8 9 7 8]], shape=(3, 5), dtype=int32) (3, 5)


##Sumation

In [179]:
#Sumation
t1 = tf.random.uniform((5, 3), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)
print(t1, t1.shape)

#Tong cac phan tu cua tensor
print(tf.math.reduce_sum(t1))
#Tinh tong theo tung cot
print(tf.math.reduce_sum(t1, axis=0))
#Tinh tong theo tung hang
print(tf.math.reduce_sum(t1, axis=1))

tf.Tensor(
[[6 3 5]
 [2 3 2]
 [6 5 6]
 [6 6 6]
 [8 9 5]], shape=(5, 3), dtype=int32) (5, 3)
tf.Tensor(78, shape=(), dtype=int32)
tf.Tensor([28 26 24], shape=(3,), dtype=int32)
tf.Tensor([14  7 17 18 22], shape=(5,), dtype=int32)


##Max and min

In [182]:
#Max and min
t1 = tf.random.uniform((5, 3), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)
print(t1, t1.shape)

print(tf.math.reduce_min(t1))
print(tf.math.reduce_max(t1))

tf.Tensor(
[[4 3 3]
 [4 6 4]
 [3 8 9]
 [4 8 7]
 [5 5 2]], shape=(5, 3), dtype=int32) (5, 3)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [183]:
print(tf.math.reduce_min(t1, axis = 0))
print(tf.math.reduce_min(t1, axis = 1))

tf.Tensor([3 3 2], shape=(3,), dtype=int32)
tf.Tensor([3 4 3 4 2], shape=(5,), dtype=int32)


# Broadcasting


In [184]:
#vector and a scalar
t1 = tf.random.uniform((5, 3), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)

print(t1, t1.shape)

t2 = 2

#broadcasting
result_multiplication = t1*t2
result_minus = t1 - t2

print(result_multiplication)
print(result_minus)

tf.Tensor(
[[6 1 6]
 [6 5 8]
 [1 9 2]
 [6 8 8]
 [6 3 6]], shape=(5, 3), dtype=int32) (5, 3)
tf.Tensor(
[[12  2 12]
 [12 10 16]
 [ 2 18  4]
 [12 16 16]
 [12  6 12]], shape=(5, 3), dtype=int32)
tf.Tensor(
[[ 4 -1  4]
 [ 4  3  6]
 [-1  7  0]
 [ 4  6  6]
 [ 4  1  4]], shape=(5, 3), dtype=int32)


In [185]:
#mtrix and vector
import torch

t1 = tf.random.uniform((5, 3), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)

t2 = tf.random.uniform((5, 3), maxval= 10, minval= 1,  dtype=tf.dtypes.int32)


print("t1:",t1)
print("t2:",t2)

t3 = t1 +t2
print("t3:",t3)

t1: tf.Tensor(
[[3 1 9]
 [1 5 7]
 [5 6 2]
 [8 4 3]
 [8 7 7]], shape=(5, 3), dtype=int32)
t2: tf.Tensor(
[[5 1 9]
 [3 3 9]
 [9 2 6]
 [7 5 4]
 [5 2 2]], shape=(5, 3), dtype=int32)
t3: tf.Tensor(
[[ 8  2 18]
 [ 4  8 16]
 [14  8  8]
 [15  9  7]
 [13  9  9]], shape=(5, 3), dtype=int32)
